name: Frambouase Deploy
run-name: Deploying to Frambouase
on:
    push:
        branches:
            - main
            - dockerize
    workflow_dispatch:
jobs:
    docker_build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3.8.0
            - name: Install QEMU
              uses: docker/setup-qemu-action@v3.3.0
            - name: Login to Docker Hub
              uses: docker/login-action@v3.3.0
              with:
                  username: leottaro
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build for arm64 and push image
              run: docker buildx build --platform linux/arm64,linux/amd64 -t leottaro/frambot:latest --push .

    frambouase_deploy:
        runs-on: self-hosted
        needs: docker_build
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2
            - name: Login to Docker Hub
              uses: docker/login-action@v3.3.0
              with:
                  username: leottaro
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Pull image
              run: docker pull leottaro/frambot:latest
            - name: Stop and remove the old container if it exists
              run: |
                  if [ "$(docker ps -q -f name=frambot)" ]; then
                    docker stop frambot
                    docker rm frambot
                  else
                    echo "No container to stop"
                  fi
            - name: Run container
              run: docker run --detach -e BOT_TOKEN=${{ secrets.BOT_TOKEN }} --name frambot --restart unless-stopped leottaro/frambot:latest
